version: 2.1
executors:
  golang:
    working_directory: &working_directory "~/goutils"
    docker:
      - image: circleci/golang:1.13
        environment:
          TZ: "Asia/Tokyo"
          GOPATH: &gopath "/home/circleci/go"

commands:
  restore_source_cache:
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-
  save_source_cache:
    steps:
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  restore_go_cache:
    steps:
      - restore_cache:
          keys:
            - go-packages-{{ .Branch }}-{{ checksum "go.sum" }}
            - go-packages-{{ .Branch }}-
  save_go_cache:
    steps:
      - save_cache:
          key: go-packages-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg"

jobs:
  prepare_source:
    executor: golang
    steps:
      - restore_source_cache
      - checkout
      - save_source_cache

  prepare_go:
    executor: golang
    steps:
      - restore_source_cache
      - checkout
      - restore_go_cache
      - run:
          name: initialize
          command: go mod tidy
      - save_go_cache

  test_go:
    executor: golang
    steps:
      - restore_source_cache
      - checkout
      - restore_go_cache
      - run:
          name: exec go test
          command: |
            go test -v ./...

workflows:
  version: 2
  test:
    jobs:
      - prepare_source
      - prepare_go:
          requires:
            - prepare_source
      - test_go:
          requires:
            - prepare_go
